### ISSUE TITLE
Intergration for the .NET MVC app widget controls

### ISSUE THREAD

**Issue by chamarajanaka** [Kentico/xperience-module-bynder#3]
### Motivation

There's no integration for widget controls at the moment

### Proposed solution

An ideal solution for the above problems.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by tomasp2** [comment]
Hi,

thanks for raising the issue. Currently, we do not intend to add Bynger integrations for widget controls in the near future. You can submit this idea to our Product management team directly via https://roadmap.kentico.com/ (Submit idea button in the top right corner).

If you like the challenge, you can add the support for widgets yourself and submit a PR.

**Comment by ondrejhenek** [comment]
Hi! Thank you for the feature request and thank you, Tomas, for the response. It's as you said. I'm closing this issue as resolved, even though it is resolved by saying "won't do for now".
